spring:
  datasource:
    password: Evaristo
    username: root
    url: jdbc:mysql://localhost/transportador?createDatabaseIfNotExist=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
