spring:
  datasource:
    password: sa
    username: Evaristo10
    url: jdbc:sqlserver://;serverName=localhost/fornecedor;instanceName=default
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    platform: mssql
  jpa:
    hibernate:
      ddl-auto: update
      
      
      
