spring:
  datasource:
    password: Evaristo
    username: root
    url: jdbc:sqlserver://localhost/fornecedor?createDatabaseIfNotExist=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
