spring:
  datasource:
   password: Evaristo
    username: root
    url: jdbc:mysql://localhost/provisor?createDatabaseIfNotExist=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: create
      
      
      
      
